name: Pulumi Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  pulumi-deploy:
    runs-on: ubuntu-latest
    environment: prod

    env:
      # Pulumi passphrase from GitHub Secrets for encrypting secrets
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Adjust the node version based on your project requirement

    - name: Install dependencies
      run: npm install

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-west-1  # Specify your AWS region
      run: echo "AWS credentials configured"  

    - name: Pulumi login to S3 backend
      run: pulumi login 's3://pulumi-state-bucket-df4d899?region=eu-west-1'

    - name: Pulumi Preview
      uses: pulumi/actions@v5
      with:
        command: preview
        stack-name: state
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Pulumi Deploy
      uses: pulumi/actions@v5
      with:
        command: up
        stack-name: state
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
